会場名をインプレスに変更
keita-ooshino/ichiyasaGitSample pull request #3
Opened 2023-10-10 02:42 UTC by ryosuke-kataoka-0812

教科書レッスン31～33用にプルリクエスト作成しました。
教科書の手順通り対応お願いいたします

2023-10-11 05:16 UTC, keita-ooshino requested changes
修正ありがとうございます！指摘のご確認と修正をお願いします。

2023-10-11 05:16 UTC, keita-ooshino commented on index.html
> +                        <p>インプレス    イベントセミナー会場</p>
「株式会社インプレス」と正式な表記にしていただけますか？

2023-10-12 03:50 UTC, ryosuke-kataoka-0812 commented on index.html
> +                        <p>インプレス    イベントセミナー会場</p>
修正いたしました。ご確認よろしくお願いいたします。

2023-10-14 03:38 UTC, keita-ooshino approved these changes

2023-10-14 03:41 UTC, merged